@server = https://super-duper-tribble-rjvvv7rxqrvc5r5j-8080.app.github.dev
@genero = {{server}}/api/generos
@autores = {{server}}/api/autores
@libros = {{server}}/api/libros
###
GET {{genero}}
###

GET {{autores}}
###

GET {{libros}}
###

GET {{server}}/api/integrantes/1/instrumento
###
GET {{server}}/api/generos/1/union